/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import BN from "bn.js";
import Contract, { contractOptions } from "web3/eth/contract";
import { EventLog, Callback, EventEmitter } from "web3/types";
import { TransactionObject, BlockType } from "web3/eth/types";
import { ContractEvent } from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export class Descriptor extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: contractOptions
  );
  clone(): Descriptor;
  methods: {
    weightDescriptors(arg0: number | string): TransactionObject<BN>;

    populationDescriptors(
      arg0: string,
      arg1: number | string
    ): TransactionObject<BN>;

    insertDescriptor(weight: number | string): TransactionObject<void>;

    getLatestUserWeight(): TransactionObject<BN>;
  };
  events: {
    WeightInserted: ContractEvent<{
      from: string;
      weight: BN;
      0: string;
      1: BN;
    }>;
    WeightRetrieved: ContractEvent<{
      from: string;
      weight: BN;
      0: string;
      1: BN;
    }>;
    allEvents: (
      options?: EventOptions,
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
